### ISSUE TITLE
Play package in chocolate is out of date

### ISSUE THREAD

**Issue by ibtwbbab** [playframework/playframework.com#135]
Hi, play framework package in chocolate is still 2.3.6 version. Could you upgrade it? Thanks!

**Comment by marcospereira** [comment]
You don't need a updated version of Play anymore, you just need a updated version of sbt:

https://chocolatey.org/packages/sbt

Since the sbt package is up to date, you can use `sbt new` to [create new projects](https://playframework.com/download#seeds) and then use `sbt` console like this:

https://playframework.com/documentation/2.5.x/PlayConsole

Anyway, I'm not a Windows users and I'm unsure about possible gotchas.

**Comment by ibtwbbab** [comment]
I got it. Thanks！
Marcos Pereira <notifications@github.com>于2017年4月3日 周一上午2:40写道：
