### ISSUE TITLE
Links on Download page not working!

### ISSUE THREAD

**Issue by mkurz** [playframework/playframework.com#138]
The download links for the `Play 2.5.x Starter Projects` (`Play Java Starter Example` and `Play Scala Starter Example`) and the `Play 2.5.x Examples` (the`Chatroom`, `Ebean` example an **all** others) are not working:
```
no template with the name play-java found
```

/cc @wsargent @gmethvin

**Comment by gmethvin** [comment]
Should be fixed now.

We at some point changed from "seed" to "starter" when labeling starter projects and didn't update the site properly. We also changed the naming scheme for other projects and since we were caching with an infinite TTL those never got updated.

We changed the names on github a while back, but I think some things on our backend example code service got updated without our knowledge.

I think if we stick to this naming scheme everything will be fine.

**Comment by mkurz** [comment]
I confirm it's fixed now.
